modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Qendolin/better-clouds/issues/new"
license = "MPL-2.0"

[[mods]]
modId = "betterclouds"
version = "${version}"
displayName = "Better Clouds"
authors = "Qendolin"
description = '''
Beautiful clouds in touch with the vanilla style.
'''
logoFile = "assets/betterclouds/icon.png"

[[dependencies.betterclouds]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterclouds]]
modId = "minecraft"
type = "required"
versionRange = "${mc_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterclouds]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.5.0,4.0.0)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "betterclouds.mixins.json"

[[mixins]]
config = "betterclouds.optional.mixins.json"